export const STUDENTS = [
  {
    name: 'Alice',
    filterType: 'Primary',
    year: 1,
    editMode: false,
    className: 'Grade 1 - A',
    subject1: 'A',
    subject2: 'B',
    subject3: 'c',
    image: 'https://picsum.photos/200/300',
  },
  {
    name: 'Bob',
    filterType: 'Primary',
    year: 1,
    editMode: false,
    className: 'Grade 1 - B',
    subject1: 'A',
    subject2: 'B',
    subject3: 'c',
    image: 'https://picsum.photos/200/300',
  },
  {
    name: 'Charlie',
    filterType: 'Primary',
    year: 2,
    editMode: false,
    className: 'Grade 2 - A',
    subject1: 'A',
    subject2: 'B',
    subject3: 'c',
    image: 'https://picsum.photos/200/300',
  },
  {
    name: 'David',
    filterType: 'Primary',
    year: 2,
    editMode: false,
    className: 'Grade 2 - B',
    subject1: 'A',
    subject2: 'B',
    subject3: 'c',
    image: 'https://picsum.photos/200/300',
  },
  {
    name: 'Eve',
    filterType: 'Secondary',
    year: 6,
    editMode: false,
    className: 'Grade 6 - A',
    subject1: 'A',
    subject2: 'B',
    subject3: 'c',
    image: 'https://picsum.photos/200/300',
  },
  {
    name: 'Frank',
    filterType: 'Secondary',
    year: 6,
    editMode: false,
    className: 'Grade 6 - B',
    subject1: 'A',
    subject2: 'B',
    subject3: 'c',
    image: 'https://picsum.photos/200/300',
  },
  {
    name: 'Grace',
    filterType: 'Secondary',
    year: 7,
    editMode: false,
    className: 'Grade 7 - A',
    subject1: 'A',
    subject2: 'B',
    subject3: 'c',
    image: 'https://picsum.photos/200/300',
  },
  {
    name: 'Helen',
    filterType: 'Secondary',
    year: 7,
    editMode: false,
    className: 'Grade 7 - B',
    subject1: 'A',
    subject2: 'B',
    subject3: 'c',
    image: 'https://picsum.photos/200/300',
  },
  {
    name: 'Ivy',
    filterType: 'Primary',
    year: 1,
    editMode: false,
    className: 'Grade 1 - C',
    subject1: 'A',
    subject2: 'B',
    subject3: 'c',
    image: 'https://picsum.photos/200/300',
  },
  {
    name: 'Jack',
    filterType: 'Primary',
    year: 2,
    editMode: false,
    className: 'Grade 2 - C',
    subject1: 'A',
    subject2: 'B',
    subject3: 'c',
    image: 'https://picsum.photos/200/300',
  },
  {
    name: 'Kevin',
    filterType: 'Secondary',
    year: 6,
    editMode: false,
    className: 'Grade 6 - C',
    subject1: 'A',
    subject2: 'B',
    subject3: 'c',
    image: 'https://picsum.photos/200/300',
  },
  {
    name: 'Linda',
    filterType: 'Secondary',
    year: 7,
    editMode: false,
    className: 'Grade 7 - C',
    subject1: 'A',
    subject2: 'B',
    subject3: 'c',
    image: 'https://picsum.photos/200/300',
  },
  {
    name: 'Mike',
    filterType: 'Primary',
    year: 3,
    editMode: false,
    className: 'Grade 3 - A',
    subject1: 'A',
    subject2: 'B',
    subject3: 'c',
    image: 'https://picsum.photos/200/300',
  },
  {
    name: 'Nancy',
    filterType: 'Primary',
    year: 3,
    editMode: false,
    className: 'Grade 3 - B',
    subject1: 'A',
    subject2: 'B',
    subject3: 'c',
    image: 'https://picsum.photos/200/300',
  },
  {
    name: 'Oliver',
    filterType: 'Primary',
    year: 4,
    editMode: false,
    className: 'Grade 4 - A',
    subject1: 'A',
    subject2: 'B',
    subject3: 'c',
    image: 'https://picsum.photos/200/300',
  },
  {
    name: 'Patricia',
    filterType: 'Primary',
    year: 4,
    editMode: false,
    className: 'Grade 4 - B',
    subject1: 'A',
    subject2: 'B',
    subject3: 'c',
    image: 'https://picsum.photos/200/300',
  },
  {
    name: 'Quincy',
    filterType: 'Primary',
    year: 5,
    editMode: false,
    className: 'Grade 5 - A',
    subject1: 'A',
    subject2: 'B',
    subject3: 'c',
    image: 'https://picsum.photos/200/300',
  },
  {
    name: 'Rachel',
    filterType: 'Primary',
    year: 5,
    editMode: false,
    className: 'Grade 5 - B',
    subject1: 'A',
    subject2: 'B',
    subject3: 'c',
    image: 'https://picsum.photos/200/300',
  },
  {
    name: 'Sam',
    filterType: 'Secondary',
    year: 8,
    editMode: false,
    className: 'Grade 8 - A',
    subject1: 'A',
    subject2: 'B',
    subject3: 'c',
    image: 'https://picsum.photos/200/300',
  },
  {
    name: 'Tina',
    filterType: 'Secondary',
    year: 8,
    editMode: false,
    className: 'Grade 8 - B',
    subject1: 'A',
    subject2: 'B',
    subject3: 'c',
    image: 'https://picsum.photos/200/300',
  },
];

export const CLASS_MODEL = [
  {
    filterType: 'Primary',
    year: 1,
    classes: ['Grade 1 - A', 'Grade 1 - B', 'Grade 1 - C'],
  },
  {
    filterType: 'Primary',
    year: 2,
    classes: [
      'Grade 2 - A',
      'Grade 2 - B',
      'Grade 2 - C',
      'Grade 2 - D',
      'Grade 2 - E',
    ],
  },
  {
    filterType: 'Primary',
    year: 3,
    classes: [
      'Grade 3 - A',
      'Grade 3 - B',
      'Grade 3 - C',
      'Grade 3 - D',
      'Grade 3 - E',
    ],
  },
  {
    filterType: 'Primary',
    year: 4,
    classes: [
      'Grade 4 - A',
      'Grade 4 - B',
      'Grade 4 - C',
      'Grade 4 - D',
      'Grade 4 - E',
    ],
  },
  {
    filterType: 'Primary',
    year: 5,
    classes: [
      'Grade 5 - A',
      'Grade 5 - B',
      'Grade 5 - C',
      'Grade 5 - D',
      'Grade 5 - E',
    ],
  },
  {
    filterType: 'Secondary',
    year: 6,
    classes: ['Grade 6 - A', 'Grade 6 - B', 'Grade 6 - C', 'Grade 6 - D'],
  },
  {
    filterType: 'Secondary',
    year: 7,
    classes: ['Grade 7 - A', 'Grade 7 - B', 'Grade 7 - C', 'Grade 7 - D'],
  },
  {
    filterType: 'Secondary',
    year: 8,
    classes: ['Grade 8 - A', 'Grade 8 - B', 'Grade 8 - C', 'Grade 8 - D'],
  },
];
